### ISSUE TITLE
Unable to use with Xcode 5.0

### ISSUE THREAD

**Issue by lrvick** [ios-driver/ios-driver#159] opened 2013-09-25 21:08 UTC
Attempted to use current 0.6.4 release with xcode 5 and encountered multiple issues. On talking to @nicegraham he mentioned the current branch currently lacks 5.0 compatibility and to try @freynaud 's refactor branch.

Went ahead and pulled latest commit and built (as of the time of this posting)

First I tried running it, it complained about being unable to copy the SDKS folder to the exciledSDKS folder. I tried sudo and chmod +rwx to no avail so I just copied it manually which at least got me further, but it still blows up when I try to driver.get('') a page.

> sudo rsync -Pav  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/{SDKs,exiledSDKs}
> 
> sudo java -jar server/target/ios-server-0.6.4-jar-with-dependencies.jar -port 4444 -simulators

```
00:17:673 INFO ApplicationStore.<init>  App archive folder:/Users/test/Sources/ios-driver/applications
00:21:234 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
00:21:837 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
00:21:877 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
00:23:140 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
00:23:743 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
00:23:767 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
00:24:650 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
00:25:241 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
00:25:266 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
00:25:303 INFO IOSServer.init
Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): true
Inspector: http://0.0.0.0:4444/inspector/
tests can access the server at http://0.0.0.0:4444/wd/hub
server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/test/Sources/ios-driver/applications' for new applications
Archived apps /Users/test/Sources/ios-driver/applications
using xcode install : /Applications/Xcode.app
using IOS version 7.0
ios >= 6.0. Safari and hybrid apps are supported.

Applications :
---------------
    CFBundleName=Safari,CFBundleVersion=8536.25
    CFBundleName=Safari,CFBundleVersion=8536.25
    CFBundleName=Safari,CFBundleVersion=9537.53

2013-09-25 16:00:25.304:INFO::jetty-7.x.y-SNAPSHOT
2013-09-25 16:00:25.795:INFO::Started SelectChannelConnector@0.0.0.0:4444
00:50:330 WARNING AppleLanguage.create  null isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
org.openqa.selenium.WebDriverException: cannot configure simulator
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_40'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.utils.SimulatorSettings.setL10N(SimulatorSettings.java:115)
    at org.uiautomation.ios.server.simulator.IOSSimulatorManager.setL10N(IOSSimulatorManager.java:185)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.start(InstrumentsApple.java:100)
    at org.uiautomation.ios.server.InstrumentsBackedNativeIOSDriver.start(InstrumentsBackedNativeIOSDriver.java:43)
    at org.uiautomation.ios.server.services.IOSDualDriver.start(IOSDualDriver.java:95)
    at org.uiautomation.ios.server.ServerSideSession.start(ServerSideSession.java:181)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:41)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:144)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:85)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:57)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:724)
Caused by: org.openqa.selenium.WebDriverException: convertion to binary pfile failed.exitCode=1
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_40'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.utils.SimulatorSettings.writeOnDisk(SimulatorSettings.java:298)
    at org.uiautomation.ios.utils.SimulatorSettings.setL10N(SimulatorSettings.java:113)
    ... 33 more
00:56:241 WARNING IOSServlet.getResponse  6094ms.   POST     /session
org.openqa.selenium.WebDriverException: Error processing response.bug.null
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_40'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_40'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:121)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:57)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:724)
Caused by: org.openqa.selenium.WebDriverException: bug.null
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_40'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:164)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:85)
    ... 24 more
Caused by: java.lang.NullPointerException
    at org.uiautomation.ios.server.simulator.IOSSimulatorManager.restoreExiledSDKs(IOSSimulatorManager.java:132)
    at org.uiautomation.ios.server.simulator.IOSSimulatorManager.cleanupDevice(IOSSimulatorManager.java:159)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.stop(InstrumentsApple.java:129)
    at org.uiautomation.ios.server.InstrumentsBackedNativeIOSDriver.stop(InstrumentsBackedNativeIOSDriver.java:50)
    at org.uiautomation.ios.server.services.IOSDualDriver.stop(IOSDualDriver.java:46)
    at org.uiautomation.ios.server.ServerSideSession.stop(ServerSideSession.java:190)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:51)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:144)
    ... 25 more
```

**Comment by DamienLyles** [comment] 2013-09-26 09:21
Are you specifying a language when you create the instance of the driver?  That resolved the issue below for me.

**Comment by lrvick** [comment] 2013-09-26 17:49
Here is the client code I am using. Adding in the language and simulator don't seem to have any impact.

``` python
from selenium import webdriver

capabilties =  webdriver.DesiredCapabilities.IPHONE
capabilties['LANGUAGE'] = 'en'
capabilties['SIMULATOR'] = True

print capabilties

driver = webdriver.Remote(
    "http://localhost:4444/wd/hub",
    capabilties
)

driver.get("http://google.com")
```

**Comment by freynaud** [comment] 2013-09-26 18:36
can you try with all the capabilities lower case  ?
You have everything we use here :
https://github.com/ios-driver/ios-driver/blob/dev/common/src/main/java/org/uiautomation/ios/IOSCapabilities.java
convention is lower case.

**Comment by freynaud** [comment] 2014-01-29 13:40
this should be resolved with the latest build 
https://dl.dropboxusercontent.com/u/24687868/ios-beta/ios-server-0.6.6-SNAPSHOT.jar
please reopen if the issue is still there.

thanks,
françois

**Closed as completed by freynaud** 2014-01-29 13:40 UTC
