### ISSUE TITLE
ios7 simulator is not launching.

### ISSUE THREAD

**Issue by nxqamar** [ios-driver/ios-driver#211] opened 2014-01-28 15:32 UTC
I strictly followed this [instruction for setup](http://ios-driver.github.io/ios-driver/setup.html) and this [instruction for safari](http://ios-driver.github.io/ios-driver/safari.html) (and tried way many permuatations beyond these instructions like downragding ios-server, xcode etc.) but i cant seem to launch ios7 simulator. I am only doing **simulator** testing, nothing to do with real device.
### My setup:

MacBook Air with OS X 10.8.5
Xcode Version 5.0.1 (5A2053)

Output of **xcodebuild -showsdks**

```
OS X SDKs:
    OS X 10.8                       -sdk macosx10.8
    OS X 10.9                       -sdk macosx10.9

iOS SDKs:
    iOS 7.0                         -sdk iphoneos7.0

iOS Simulator SDKs:
    Simulator - iOS 6.1             -sdk iphonesimulator6.1
    Simulator - iOS 7.0             -sdk iphonesimulator7.0
```

I can manually invoke the ios7 simulator through Xcode though. This seems like a very straight forward process and I am not sure what I might be doing wrong.
### My code to call webdriver

```
    public synchronized static WebDriver getIOSDriver() {
        if (driver == null) {
            DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
            safari.setCapability(IOSCapabilities.SIMULATOR, true);
            safari.setCapability("simulatorVersion", "7.0");
            safari.setCapability("sdkVersion", "7.0");

            try {
                driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), safari);
                driver.get("http://www.ebay.co.uk/");

                System.out.println(driver.getTitle());
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

        }
        return driver;
    }
```
### Launching of ios-driver server

```
-jar ios-server-0.6.5-jar-with-dependencies.jar -simulators -port 444
```

and now my server logs and maven build logs are stuck in the terminal and in eclipse console individually:
### ios-driver server logs

```
25:22:124 WARNING DefaultCommandListener.stderr  2014-01-27 19:25:22.123 instruments[12903:707] -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff7a74b500
25:22:125 WARNING DefaultCommandListener.stderr  2014-01-27 19:25:22.125 instruments[12903:707] Exception during preparation: -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff7a74b500
25:22:131 WARNING DefaultCommandListener.stderr  2014-01-27 19:25:22.131 instruments[12903:707] *** Assertion failure in -[UIAInstrument _startAgentForApp:withPID:], /SourceCache/AutomationInstrument/AutomationInstrument-1000/Classes/UIAInstrument-Simulator.m:116
25:22:133 WARNING DefaultCommandListener.stderr  2014-01-27 19:25:22.132 instruments[12903:707] Automation Instrument ran into an exception while trying to run the script.  NSInternalInconsistencyException
```
### Maven build logs:

```
-------------------------------------------------------
T E S T S
-------------------------------------------------------

Running com.pxm.ia.app.RunCukesIT
Jan 27, 2014 7:25:16 PM com.pxm.app.utils.BddUtils getBrowserType
INFO: browser type ::::ios
Jan 27, 2014 7:25:16 PM com.pxm.app.utils.BrowserDriver getCurrentDriver
INFO: Browser used::::ios
```

where "ios" is the build param for maven
**It eventually times out**

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Running com.pxm.app.RunCukesIT
Jan 27, 2014 7:25:16 PM com.pxn.app.utils.BddUtils getBrowserType
INFO: browser type ::::ios
Jan 27, 2014 7:25:16 PM com.pxm.app.utils.BrowserDriver getCurrentDriver
INFO: Browser used::::ios
org.openqa.selenium.SessionNotCreatedException: java.net.SocketTimeoutException: Read timed out
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_45'
Driver info: driver.version: RemoteWebDriver
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_45'
Driver info: driver.version: unknown
Command duration or timeout: 664.88 seconds
```
### JSON from accessing http://localhost:4444/wd/hub/status

```
{
  "class": "org.openqa.selenium.remote.Response",
  "hCode": 1480457355,
  "sessionId": null,
  "state": null,
  "status": 0,
  "value": {
    "build": {
      "revision": "120cf4311807e2e137e519f4c4877cf6340d0cbc",
      "time": "20130927-1435",
      "version": "0.6.5"
    },
    "ios": {"simulatorVersion": "7.0"},
    "java": {"version": "1.7.0_45"},
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.8.5"
    },
    "state": "success",
    "supportedApps": [{
      "CFBundleDevelopmentRegion": "English",
      "CFBundleDisplayName": "Safari",
      "CFBundleExecutable": "MobileSafari",
      "CFBundleIcons": {"CFBundlePrimaryIcon": {
        "CFBundleIconFiles": [
          "icon-spotlight~ipad.png",
          "icon-table~ipad.png",
          "icon-about~ipad.png",
          "icon-table~ipad.png",
          "icon-spotlight@2x.png",
          "icon-table@2x.png",
          "icon~ipad.png",
          "icon-about@2x.png",
          "icon@2x~iphone.png",
          "icon@2x~ipad.png"
        ],
        "UIPrenderedIcon": true
      }},
      "CFBundleIdentifier": "com.apple.mobilesafari",
      "CFBundleInfoDictionaryVersion": "6.0",
      "CFBundlePackageType": "APPL",
      "CFBundleShortVersionString": "7.0",
      "CFBundleSignature": "????",
      "CFBundleSupportedPlatforms": ["iPhoneSimulator"],
      "CFBundleURLTypes~ipad": [
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "Web App URL",
          "CFBundleURLSchemes": ["webclip"]
        },
        {
          "CFBundleURLName": "Web site URL",
          "CFBundleURLSchemes": [
            "http",
            "https"
          ]
        },
        {
          "CFBundleURLName": "FTP URL",
          "CFBundleURLSchemes": ["ftp"]
        },
        {
          "CFBundleURLName": "Web Search URL",
          "CFBundleURLSchemes": ["x-web-search"]
        },
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "MobileSafari Tab URL",
          "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
        }
      ],
      "CFBundleURLTypes~iphone": [
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "Web App URL",
          "CFBundleURLSchemes": ["webclip"]
        },
        {
          "CFBundleURLName": "Web site URL",
          "CFBundleURLSchemes": [
            "http",
            "https"
          ]
        },
        {
          "CFBundleURLName": "Radar URL",
          "CFBundleURLSchemes": [
            "rdar",
            "radar"
          ]
        },
        {
          "CFBundleURLName": "FTP URL",
          "CFBundleURLSchemes": ["ftp"]
        },
        {
          "CFBundleURLName": "Web Search URL",
          "CFBundleURLSchemes": ["x-web-search"]
        },
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "MobileSafari Tab URL",
          "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
        }
      ],
      "CFBundleURLTypes~ipod": [
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "Web App URL",
          "CFBundleURLSchemes": ["webclip"]
        },
        {
          "CFBundleURLName": "Web site URL",
          "CFBundleURLSchemes": [
            "http",
            "https"
          ]
        },
        {
          "CFBundleURLName": "Radar URL",
          "CFBundleURLSchemes": [
            "rdar",
            "radar"
          ]
        },
        {
          "CFBundleURLName": "FTP URL",
          "CFBundleURLSchemes": ["ftp"]
        },
        {
          "CFBundleURLName": "Web Search URL",
          "CFBundleURLSchemes": ["x-web-search"]
        },
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "MobileSafari Tab URL",
          "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
        }
      ],
      "CFBundleVersion": "9537.53",
      "DTPlatformName": "iphonesimulator",
      "DTSDKName": "iphonesimulator7.0",
      "LSRequiresIPhoneOS": true,
      "MallocBehavior": {"NanoAllocator": false},
      "SBMatchingApplicationGenres": [
        "Productivity",
        "Utilities"
      ],
      "SBUsesNetwork": 3,
      "SafariProductVersion": "7.0",
      "UIApplicationDisableLegacyAutorotationKey": true,
      "UIBackgroundModes": [
        "audio",
        "continuousFallback"
      ],
      "UIBackgroundStyle": "UIBackgroundStyleDarkBlur",
      "UIDeviceFamily": [
        2,
        1
      ],
      "UIHasPrefs": true,
      "UIStatusBarTintParameters": {"UINavigationBar": {"Style": "UIBarStyleDefault"}},
      "UISupportedInterfaceOrientations": [
        "UIInterfaceOrientationPortrait",
        "UIInterfaceOrientationLandscapeLeft",
        "UIInterfaceOrientationLandscapeRight"
      ],
      "UISupportedInterfaceOrientations~ipad": [
        "UIInterfaceOrientationPortrait",
        "UIInterfaceOrientationLandscapeLeft",
        "UIInterfaceOrientationLandscapeRight",
        "UIInterfaceOrientationPortraitUpsideDown"
      ],
      "UIViewControllerBasedStatusBarAppearance": true,
      "applicationPath": "/Users/aboutuser/.ios-driver/safariCopies/safari-7.0.app",
      "device": "iphone",
      "deviceAlt": [
        "ipad",
        "iphone",
        "ipod"
      ],
      "device_Alt": [
        "iphone",
        "ipad"
      ],
      "resources": {"CFBundleIconFile": "/wd/hub/resources/hash=2134756163"},
      "sdkVersion": "7.0",
      "sdkVersion_Alt": [
        "5.0",
        "5.1",
        "6.0",
        "6.1"
      ],
      "simulator": true,
      "supportedLanguages": [
        "hr",
        "ro",
        "ca",
        "vi",
        "tr",
        "fr",
        "unknown",
        "hu",
        "unknown",
        "th",
        "id",
        "pt-PT",
        "en-GB",
        "fi",
        "unknown",
        "sv",
        "it",
        "sk",
        "ja",
        "uk",
        "es",
        "da",
        "ms",
        "ko",
        "ar",
        "he",
        "en",
        "nl",
        "cs",
        "el",
        "pl",
        "pt",
        "ru",
        "de"
      ],
      "timeHack": false,
      "variation": "Regular"
    }]
  }
}
```

Any help would be highly appreciated.

**Comment by freynaud** [comment] 2014-01-28 15:39
I think xcode 5.0.1 didn't work properly with instruments.
I'm using xcode 5.0.2
The following code works fine ( using the dev branch )

DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
    safari.setCapability(IOSCapabilities.SIMULATOR, true);
    safari.setCapability("simulatorVersion", "7.0.3");
    safari.setCapability("sdkVersion", "7.0.3");

```
  RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), safari);
  driver.get("http://www.ebay.co.uk/");
```

**Comment by nxqamar** [comment] 2014-01-28 16:22
So I upgraded to Xcode 5.0.2 and upon launch Xcode installed the missing components etc and I am seeing the following exception about **missing SDK 7.0.3** which makes me wonder if OS X 10.9 is mandatory for SDK 7.0.3.. 

```
...
...
org.openqa.selenium.SessionNotCreatedException: SDK 7.0.3 not installed on this machine.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_45'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_45'
Driver info: driver.version: unknown
Command duration or timeout: 534 milliseconds
Build info: version: '2.37.1', revision: 'a7c61cbd68657e133ae96672cf995890bad2ee42', time: '2013-10-21 09:08:07'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_45'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
...
...
```

This was my output of **xcodebuild -showsdks**

```
OS X SDKs:
    OS X 10.8                       -sdk macosx10.8
    OS X 10.9                       -sdk macosx10.9

iOS SDKs:
    iOS 7.0                         -sdk iphoneos7.0

iOS Simulator SDKs:
    Simulator - iOS 6.1             -sdk iphonesimulator6.1
    Simulator - iOS 7.0             -sdk iphonesimulator7.0

new-host:0.6.5 nqamar$ xcodebuild -showsdks
OS X SDKs:
    OS X 10.8                       -sdk macosx10.8
    OS X 10.9                       -sdk macosx10.9

iOS SDKs:
    iOS 7.0                         -sdk iphoneos7.0

iOS Simulator SDKs:
    Simulator - iOS 6.1             -sdk iphonesimulator6.1
    Simulator - iOS 7.0             -sdk iphonesimulator7.0
```

**Comment by freynaud** [comment] 2014-01-29 12:52
this has been fixed in the current dev branch.
Can you try https://dl.dropboxusercontent.com/u/24687868/ios-beta/ios-server-0.6.6-SNAPSHOT.jar
and let me know if it fixes your issue ?

thanks,
François

**Comment by nxqamar** [comment] 2014-01-29 16:08
@freynaud We rebuilt from the dev branch yesterday and tried the following code and it worked. Besides the new server jar another main difference was use of **RemoteIOSDriver** instead of **RemoteWebDriver**. I had to reverse look up **/src/test/java/org/uiautomation/ios/selenium
/BaseSeleniumTest.java** as those tests were seem to be working on my machine.

### My new driver code

```
public synchronized static WebDriver getIOSDriver() {
if (driver == null) {
IOSCapabilities safari = IOSCapabilities.iphone("Safari");
safari.setCapability(IOSCapabilities.SIMULATOR, true);
// safari.setCapability("simulatorVersion", "7.0");
safari.setCapability("sdkVersion", "7.0.3");
// safari.setCapability("variation", "Retina4");

try {
driver = new RemoteIOSDriver(new URL("http://localhost:4450/wd/hub"), safari);
driver.get("http://www.ebay.co.uk/");
System.out.println(driver.getTitle());
} catch (Exception e) {
// TODO Auto-generated catch block
e.printStackTrace();
}

}
return driver;
}
```

Do you think the documentation [here](http://ios-driver.github.io/ios-driver/safari.html) needs to be updated accordingly to reflect the use of **RemoteIOSDriver**?

I am gonna go ahead and try your latest 0.6.6 with **RemoteWebDriver**.

Thanks for all your help!!!

**Closed as completed** 2014-01-29 16:10 UTC

**Comment by nxqamar** [comment] 2014-01-29 17:23
@freynaud Hey can you please give me the dependencies jar instead? I am getting 

```
no main manifest attribute, in ios-server-0.6.6-SNAPSHOT.jar
```

**Comment by freynaud** [comment] 2014-01-29 17:28
yes I can : https://dl.dropboxusercontent.com/u/24687868/ios-beta/ios-server-0.6.6-SNAPSHOT-jar-with-dependencies.jar

**Comment by nxqamar** [comment] 2014-01-29 18:51
@freynaud I have an update for you.
I used the latest (0.6.6) that you provided me and it works for **RemoteWebDriver** as well, both iphone and ipad simulators! I had to add an extra capability for retina variation for iphone though. 

My steps (as a reference for someone running in to same issue):
- Build latest **ios-server-0.6.6-SNAPSHOT-jar-with-dependencies.jar** jar off of main branch or get it from the ios-driver repository.
- chmod -R 777 /Users/aboutuser/.ios-driver/safariCopies/
- Use either **RemoteIOSDriver or RemoteWebDriver** in your driver init code (think inheritance).
- Add this capability

```
safari.setCapability("variation", "Retina4");
```

otherwise I was getting this exception

```
org.openqa.selenium.WebDriverException: iPhone variation incompatible with SDK 7.0.3, a compatible variation is Retina4
```
- Make sure there is no stale **launchd_sim** process
- Start the ios-server

```
java -jar ios-server-0.6.6-SNAPSHOT-jar-with-dependencies.jar -simulators -port 4450
```

It should output something like:

```
02:51:232 INFO ApplicationStore.<init>  App archive folder:/opt/ios-driver/applications
02:53:143 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled (enabled by -simulators flag): true
Inspector: http://0.0.0.0:4450/inspector/
Tests can access the server at http://0.0.0.0:4450/wd/hub
Server status: http://0.0.0.0:4450/wd/hub/status
Connected devices: http://0.0.0.0:4450/wd/hub/devices/all
Applications: http://0.0.0.0:4450/wd/hub/applications/all
Capabilities: http://0.0.0.0:4450/wd/hub/capabilities/all
Monitoring '/opt/ios-driver/applications' for new applications
Archived apps: /opt/ios-driver/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20140129-1350,sha:d698bccd3fade730c95785bd0ddf7e18b0dd3474)
Running on: Mac OS X 10.8.5 (x86_64)
Using java: 1.7.0_45
Using Xcode install: /Applications/Xcode.app
Using instruments: version:5.0.1, build: 51168
Using iOS version 7.0.3
iOS >= 6.0. Safari and hybrid apps are supported.

Applications :
--------------- 
    CFBundleName=Safari,CFBundleVersion=8536.25,/Users/aboutuser/.ios-driver/safariCopies/safari-6.1.app
    CFBundleName=Safari,CFBundleVersion=9537.53,/Users/aboutuser/.ios-driver/safariCopies/safari-7.0.3.app

2014-01-29 13:02:53.240:INFO::jetty-7.x.y-SNAPSHOT
2014-01-29 13:02:53.328:INFO::Started SelectChannelConnector@0.0.0.0:4450
```
- My latest driver init code:

```
    public synchronized static WebDriver getIOSDriver() {
        if (driver == null) {
            IOSCapabilities safari = IOSCapabilities.iphone("Safari");
            safari.setCapability(IOSCapabilities.SIMULATOR, true);
            safari.setCapability("sdkVersion", "7.0.3");
            safari.setCapability("variation", "Retina4");

            try {
                driver = new RemoteWebDriver(new URL("http://localhost:4450/wd/hub"), safari);
                driver.get("http://www.ebay.co.uk/");
                System.out.println(driver.getTitle());
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
        return driver;
    }

```
- Code modification to invoke ipad simulator:

```
    public synchronized static WebDriver getIOSDriver() {
        if (driver == null) {
            IOSCapabilities safari = IOSCapabilities.ipad("Safari");

            safari.setCapability(IOSCapabilities.SIMULATOR, true);
            safari.setCapability("sdkVersion", "7.0.3");
            try {
                driver = new RemoteWebDriver(new URL("http://localhost:4450/wd/hub"), safari);
                driver.get("http://www.ebay.co.uk/");
                System.out.println(driver.getTitle());
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
        return driver;
    }
```

Note: If I retained following capability for ipad simulator

```
safari.setCapability("variation", "Retina4");
```

then i get the following exception:

```
org.openqa.selenium.WebDriverException: Unsupported device type/variation ipad/Retina4
```

I really appreciate for your help and if I can be of any help in terms of documentation/wiki modifications etc., just let me know.

**Comment by benzaremean** [comment] 2014-02-27 15:13
@freynaud any chance I can get the 0.6.6-SNAPSHOT.jar?

I am also getting the no manifest attribute, in build-0.6.6-SNAPSHOT.jar when I try to run locally created jar

**Comment by benzaremean** [comment] 2014-02-27 15:53
@nxqamar @freynaud any chance I can get the 0.6.6-SNAPSHOT.jar? I am having a hellish time trying to build successfully

**Comment by nxqamar** [comment] 2014-02-27 18:36
@jamin79  Try these: 
https://www.dropbox.com/s/cfavg3f481yf195/ios-server-0.6.5-jar-with-dependencies-WORKING.jar
https://www.dropbox.com/s/apekgh2gxq22ryu/ios-server-0.6.6-SNAPSHOT-jar-with-dependencies.jar

I ended up using 0.6.5 version (the above one) and it did the job for me or at least resolved the issues I was facing.

**Comment by igrama** [comment] 2014-02-27 19:38
can you please share me the dependencies jar instead? 
I build jar from dev branch but I am constantly getting error:

no main manifest attribute, in ios-server-0.6.6-SNAPSHOT.jar

**Comment by nxqamar** [comment] 2014-02-27 19:40
@igrama  I have shared the dependencies jars in the above comment.

**Comment by igrama** [comment] 2014-02-27 19:41
just saw it, thanks

**Comment by igrama** [comment] 2014-02-27 21:15
To register ios-driver on Selenium Grid should I launch Selenium Hub with IOSRemoteProxy?
Or it should work without that IOSRemoteProxy as well?

The reason I am asking is that I am unable successfully run any test with ios-server-0.6.6-SNAPSHOT( with dependencies) through Selenium Grid (with proxy or w/o)

 I tried already many variants of driver instance with capabilities and none works.

I run ios-server on Selenium Grid with command:
java -jar ios-server-0.6.6-SNAPSHOT-jar-with-dependencies.jar -hub http://selenium_hub_ip:4444/grid/register -port 5555 -host ip_Mac_where_ios-server_runs -simulators

The errors I constantly have is about: 
Caused by: org.openqa.selenium.SessionNotCreatedException: Didn't get the capability back.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'

Appreciate any advice

**Comment by benzaremean** [comment] 2014-02-28 14:10
@nxqamar thanks.

**Comment by spatchamatla01** [comment] 2014-03-11 20:50
@nxqamar, i tried your suggestion, but getting NullPointerException

org.openqa.selenium.WebDriverException: Cannot find /instruments_no_delay/5.1/55044/instruments.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.extractFromJar(InstrumentsNoDelayLoader.java:91)
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.extract(InstrumentsNoDelayLoader.java:75)
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.<init>(InstrumentsNoDelayLoader.java:43)
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.getInstance(InstrumentsNoDelayLoader.java:53)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.getInstrumentsClient(InstrumentsApple.java:210)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.createInstrumentCommand(InstrumentsApple.java:177)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.<init>(InstrumentsApple.java:87)
    at org.uiautomation.ios.server.services.InstrumentsFactory.getInstruments(InstrumentsFactory.java:48)
    at org.uiautomation.ios.server.InstrumentsBackedNativeIOSDriver.<init>(InstrumentsBackedNativeIOSDriver.java:33)
    at org.uiautomation.ios.server.services.IOSDualDriver.start(IOSDualDriver.java:104)
    at org.uiautomation.ios.server.ServerSideSession.start(ServerSideSession.java:233)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:45)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:137)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:81)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:56)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:744)
48:42:522 SEVERE IOSServlet.getResponse  POST:/session
    body:{"desiredCapabilities":{"simulator":true,"CFBundleName":"Safari","locale":"en_GB","timeHack":false,"device":"ipad","language":"en","sdkVersion":"7.1"}}  in 1035ms
48:42:527 WARNING IOSServlet.doPost  org.openqa.selenium.WebDriverException: Error processing response.bug.null
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: unknown
