### ISSUE TITLE
Server getting Killed after executing few scripts

### ISSUE THREAD

**Issue by Bhuvanavd** [ios-driver/ios-driver#290] opened 2014-09-16 11:35 UTC
I'm executing the below mentioned jar command in the mac mini,
java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -port 4444 -sessionTimeout 30000

After executing few scripts, the server is getting killed, but the simulator is still active.

Observed in the console of macmini:
Killed: 9 ( PFB attachment of console )
![mac](https://cloud.githubusercontent.com/assets/7911749/4286476/8b50d306-3d95-11e4-9e1d-ec604935aeeb.PNG)

Kindly help me in resolving this issue!

Thanks,
Bhuvana

**Comment by bijoyv** [comment] 2014-10-09 10:28
Looks like MobileSafari is having issue (WebKitSeemsCorruptedException). If the application works well without any delay manually, can you post steps/code to reproduce the problem.

**Comment by mach6** [comment] 2015-03-11 19:03
@Bhuvanavd  closing this due to no follow-up

**Closed as completed by mach6** 2015-03-11 19:03 UTC
